galaxy_info:
  author: paulo@redhat.com
  description: In memory inventory role
  company: Red Hat
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
