---
- import_playbook: in_memory_inventory.yml

- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false
  tags:
    - load_balancers

  tasks:
    - include_role:
        name: haproxy
