---
- import_playbook: in_memory_inventory.yml

- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers

  tasks:
    - import_role:
        name: postgres 	
