---
- import_playbook: in_memory_inventory.yml

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask

  tasks:
    - import_role:
        name: webapp
