- name: Deploy OSP Instances
  import_playbook: deploy_osp_infra.yml

- name: Ensure instances are alive
  import_playbook: ping_instances.yml

- name: Deploy Post config OSP instances
  import_playbook: deploy_post_config.yml

- name: Deploy Postgres
  import_playbook: deploy_postgres.yml

- name: Deploy HAProxy 
  import_playbook: deploy_haproxy.yml

- name: Deploy Webapp
  import_playbook: deploy_webapp.yml

- name: Smoke tests
  import_playbook: smoke_tests.yml
  