- block:
  - name: DNS IP updated
    lineinfile:
      state: present
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: "{{ item }}"
    loop:
      - PEERDNS=no
      - DNS1={{ dns }}
    register: network_update
  
  - name: restart network manager
    service:
      name: NetworkManager
      state: restarted
    when: network_update.changed | bool

  - name: DEBUG VARS
    debug:
      msg: 
        - "HOSTVARS: {{ hostvars[item]['ansible_host'] }}"
    loop: "{{ hostvars['all'] }}"

  - name: Populate /etc/hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts

  - name: install katello-ca-consumer package
    yum:
      name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
      state: present
      disable_gpg_check: true
  
  - name: register system and attach subs
    redhat_subscription:
      state: present
      activationkey: "{{ satellite_activationkey }}"
      org_id: "{{ satellite_org }}"
