---
- name: Generate HOT template
  template:
    src: hot.yml.j2 
    dest: /tmp/hot.yml 

- name: Create Openstack simple Heat stack
  openstack.cloud.stack:
    name: base-stack-{{ 99999 | random }}
    state: present
    template: /tmp/hot.yml
  register: stack_create

- debug:
    msg: "{{ stack_create }}"
